
export const metadata={
    title:"next.js",
    description: "generated by next.js"
};
export default function RootLayout({
    children,
}:{
    children: React.ReactNode
}) {
    return(
        <html lang="en">
            <body className="antialiased">
                {children}
            </body>
        </html>
    )
}